.PHONY: clean All

All:
	@echo "----------Building project:[ challenge1 - Debug ]----------"
	@cd "challenge1" && "$(MAKE)" -f  "challenge1.mk"
clean:
	@echo "----------Cleaning project:[ challenge1 - Debug ]----------"
	@cd "challenge1" && "$(MAKE)" -f  "challenge1.mk" clean
